# Generated by Django 5.2.8 on 2026-03-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninjatab_marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistPageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Waitlist Page View",
                "verbose_name_plural": "Waitlist Page Views",
                "ordering": ["-created_at"],
            },
        ),
    ]
