# Generated by Django 5.2.8 on 2026-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninjatab_marketing", "0002_waitlistpageview"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistentry",
            name="invite_sent",
            field=models.BooleanField(default=False),
        ),
    ]
