# Generated by Django 5.2.8 on 2026-02-26 22:06

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CAD", "Canadian Dollar"),
                            ("TRY", "Turkish Lira"),
                            ("PLN", "Polish Złoty"),
                            ("CZK", "Czech Crown"),
                            ("AUD", "Australian Dollar"),
                            ("CHF", "Swiss Franc"),
                            ("HUF", "Hungarian Forint"),
                            ("BGN", "Bulgarian Lev"),
                            ("MXN", "Mexican Peso"),
                            ("THB", "Thai Baht"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CAD", "Canadian Dollar"),
                            ("TRY", "Turkish Lira"),
                            ("PLN", "Polish Złoty"),
                            ("CZK", "Czech Crown"),
                            ("AUD", "Australian Dollar"),
                            ("CHF", "Swiss Franc"),
                            ("HUF", "Hungarian Forint"),
                            ("BGN", "Bulgarian Lev"),
                            ("MXN", "Mexican Peso"),
                            ("THB", "Thai Baht"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Exchange rate: 1 from_currency = rate * to_currency",
                        max_digits=12,
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(
                        help_text="Date and time when this rate became effective"
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "-effective_date"],
                        name="currencies__from_cu_d5f08b_idx",
                    )
                ],
                "unique_together": {("from_currency", "to_currency", "effective_date")},
            },
        ),
    ]
