# Generated by Django 6.0.5 on 2026-05-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0002_exchangerate_usd_base"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="exchangerate",
            new_name="currencies__currenc_1feeef_idx",
            old_name="currencies__currenc_idx",
        ),
    ]
