# Generated by Django 6.0.5 on 2026-05-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0005_alter_exchangerate_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="rate",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Exchange rate: 1 USD = rate * currency",
                max_digits=20,
            ),
        ),
    ]
