# Generated by Django 5.2.8 on 2026-04-10 10:10

import datetime
import django.db.models.deletion
import uuid
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("tabs", "0001_initial"),
        ("tabs", "0002_contact"),
        ("tabs", "0003_tab_is_pro"),
        ("tabs", "0004_add_translated_name_to_lineitem"),
        ("tabs", "0005_add_receipt_scan_count_to_tab"),
        ("tabs", "0006_add_receipt_image_url_to_bill"),
        ("tabs", "0007_personlineitemclaim_settlement_amount"),
        ("tabs", "0008_add_settlement_currency_settled_total"),
        ("tabs", "0009_add_pagination_and_query_indexes"),
        ("tabs", "0010_currency_fields_to_integer"),
        ("tabs", "0011_remove_bill_tabs_bill_created_b69752_idx_and_more"),
        ("tabs", "0012_alter_bill_options_bill_receipt_image_key"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CAD", "Canadian Dollar"),
                            ("TRY", "Turkish Lira"),
                            ("PLN", "Polish Złoty"),
                            ("CZK", "Czech Crown"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("archived", "Archived")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "split_type",
                    models.CharField(
                        choices=[("shares", "Shares"), ("value", "Value")],
                        default="shares",
                        max_length=10,
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="tabs.bill",
                    ),
                ),
                (
                    "translated_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "default_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CAD", "Canadian Dollar"),
                            ("TRY", "Turkish Lira"),
                            ("PLN", "Polish Złoty"),
                            ("CZK", "Czech Crown"),
                        ],
                        default="GBP",
                        max_length=3,
                    ),
                ),
                (
                    "settlement_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CAD", "Canadian Dollar"),
                            ("TRY", "Turkish Lira"),
                            ("PLN", "Polish Złoty"),
                            ("CZK", "Czech Crown"),
                        ],
                        default="GBP",
                        help_text="Currency used for calculating settlements",
                        max_length=3,
                    ),
                ),
                ("is_settled", models.BooleanField(default=False)),
                ("invite_code", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tabs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_pro", models.BooleanField(default=False)),
                ("receipt_scan_count", models.PositiveIntegerField(default=0)),
                (
                    "settlement_currency_settled_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total spent in settlement currency, snapshotted at settlement time",
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="tab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="tabs.tab",
            ),
        ),
        migrations.CreateModel(
            name="TabPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="tabs.tab",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tab_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("tab", "name")},
            },
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CAD", "Canadian Dollar"),
                            ("TRY", "Turkish Lira"),
                            ("PLN", "Polish Złoty"),
                            ("CZK", "Czech Crown"),
                        ],
                        max_length=3,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="tabs.tab",
                    ),
                ),
                (
                    "from_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements_as_payer",
                        to="tabs.tabperson",
                    ),
                ),
                (
                    "to_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements_as_payee",
                        to="tabs.tabperson",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills_created",
                to="tabs.tabperson",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills_paid",
                to="tabs.tabperson",
            ),
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_of",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["contact_user__first_name", "contact_user__last_name"],
                "unique_together": {("owner", "contact_user")},
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="receipt_image_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="PersonLineItemClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "split_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Number of shares or direct value depending on split_type",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The actual currency amount this person owes",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("has_claimed", models.BooleanField(default=False)),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_claims",
                        to="tabs.lineitem",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_item_claims",
                        to="tabs.tabperson",
                    ),
                ),
                (
                    "settlement_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="calculated_amount converted to the tab's settlement_currency",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("person", "line_item")},
            },
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["-created_at", "-id"], name="tabs_bill_created_b69752_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tab",
            index=models.Index(
                fields=["-created_at", "-id"], name="tabs_tab_created_8d5774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tabperson",
            index=models.Index(
                fields=["tab", "user"], name="tabs_tabper_tab_id_659d4e_idx"
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="value",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="personlineitemclaim",
            name="split_value",
            field=models.IntegerField(
                blank=True,
                help_text="Number of shares (SHARES mode) or minor currency units (VALUE mode)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personlineitemclaim",
            name="calculated_amount",
            field=models.IntegerField(
                blank=True,
                help_text="The actual currency amount this person owes, in minor units",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personlineitemclaim",
            name="settlement_amount",
            field=models.IntegerField(
                blank=True,
                help_text="calculated_amount converted to the tab's settlement_currency, in minor units",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="settlement",
            name="amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="tab",
            name="settlement_currency_settled_total",
            field=models.IntegerField(
                blank=True,
                help_text="Total spent in settlement currency (minor units), snapshotted at settlement time",
                null=True,
            ),
        ),
        migrations.RemoveIndex(
            model_name="bill",
            name="tabs_bill_created_b69752_idx",
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["-date", "-id"], name="tabs_bill_date_530e90_idx"
            ),
        ),
        migrations.AlterModelOptions(
            name="bill",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AddField(
            model_name="bill",
            name="receipt_image_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
