# Generated by Django 5.2.8 on 2025-11-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personlineitemclaim",
            name="claimed_amount",
        ),
        migrations.AddField(
            model_name="personlineitemclaim",
            name="calculated_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The actual currency amount this person owes",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="personlineitemclaim",
            name="is_unsure",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personlineitemclaim",
            name="split_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Number of shares or direct value depending on split_type",
                max_digits=10,
                null=True,
            ),
        ),
    ]
