# Generated by Django 5.2.8 on 2026-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="is_pro",
            field=models.BooleanField(default=False),
        ),
    ]
