# Generated by Django 5.2.8 on 2025-11-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0002_remove_personlineitemclaim_claimed_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tab",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
