# Generated by Django 5.2.8 on 2026-03-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0003_tab_is_pro"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="translated_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
