# Generated by Django 5.2.8 on 2025-11-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0003_alter_bill_currency_alter_tab_default_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
