# Generated by Django 5.2.8 on 2026-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0004_add_translated_name_to_lineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="receipt_scan_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
