# Generated by Django 5.2.8 on 2025-11-06 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0004_alter_bill_date_alter_bill_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personlineitemclaim",
            name="is_unsure",
        ),
        migrations.AlterField(
            model_name="bill",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="bill",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
