# Generated by Django 5.2.8 on 2025-11-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0005_remove_personlineitemclaim_is_unsure_alter_bill_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tab",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                ],
                default="GBP",
                max_length=3,
            ),
        ),
    ]
