# Generated by Django 5.2.8 on 2026-03-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0005_add_receipt_scan_count_to_tab"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="receipt_image_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
