# Generated by Django 5.2.8 on 2026-03-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0006_add_receipt_image_url_to_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="personlineitemclaim",
            name="settlement_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="calculated_amount converted to the tab's settlement_currency",
                max_digits=10,
                null=True,
            ),
        ),
    ]
