# Generated by Django 5.2.8 on 2026-04-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0007_personlineitemclaim_settlement_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="settlement_currency_settled_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total spent in settlement currency, snapshotted at settlement time",
                max_digits=12,
                null=True,
            ),
        ),
    ]
