# Generated by Django 5.2.8 on 2025-11-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0007_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="settlement_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                ],
                default="GBP",
                help_text="Currency used for calculating settlements",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CAD", "Canadian Dollar"),
                            ("TRY", "Turkish Lira"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("JPY", "Japanese Yen"),
                            ("CAD", "Canadian Dollar"),
                            ("TRY", "Turkish Lira"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Exchange rate: 1 from_currency = rate * to_currency",
                        max_digits=12,
                    ),
                ),
                (
                    "effective_date",
                    models.DateTimeField(
                        help_text="Date and time when this rate became effective"
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "-effective_date"],
                        name="tabs_exchan_from_cu_2b6dc1_idx",
                    )
                ],
                "unique_together": {("from_currency", "to_currency", "effective_date")},
            },
        ),
    ]
