# Generated by Django 5.2.8 on 2026-02-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0008_tab_settlement_currency_exchangerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
