# Generated by Django 5.2.8 on 2026-04-03 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0008_add_settlement_currency_settled_total"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["-created_at", "-id"], name="tabs_bill_created_b69752_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tab",
            index=models.Index(
                fields=["-created_at", "-id"], name="tabs_tab_created_8d5774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tabperson",
            index=models.Index(
                fields=["tab", "user"], name="tabs_tabper_tab_id_659d4e_idx"
            ),
        ),
    ]
