# Generated by Django 5.2.8 on 2026-02-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0009_settlement_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="is_closed",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="is_closed",
        ),
    ]
