# Generated by Django 5.2.8 on 2026-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0010_currency_fields_to_integer"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bill",
            name="tabs_bill_created_b69752_idx",
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["-date", "-id"], name="tabs_bill_date_530e90_idx"
            ),
        ),
    ]
