# Generated by Django 5.2.8 on 2026-04-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0011_remove_bill_tabs_bill_created_b69752_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AddField(
            model_name="bill",
            name="receipt_image_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
