# Generated by Django 5.2.8 on 2026-02-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0011_tab_created_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tabperson",
            unique_together={("tab", "email"), ("tab", "name")},
        ),
    ]
