# Generated by Django 5.2.8 on 2026-04-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tabs",
            "0001_initial_squashed_0012_alter_bill_options_bill_receipt_image_key",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
