# Generated by Django 5.2.8 on 2026-02-22 19:59

import uuid
from django.db import migrations, models


def populate_invite_codes(apps, schema_editor):
    Tab = apps.get_model("tabs", "Tab")
    for tab in Tab.objects.all():
        tab.invite_code = uuid.uuid4()
        tab.save(update_fields=["invite_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0012_alter_tabperson_unique_together"),
    ]

    operations = [
        # Step 1: add nullable (no unique constraint yet) so existing rows can exist
        migrations.AddField(
            model_name="tab",
            name="invite_code",
            field=models.UUIDField(null=True, blank=True),
        ),
        # Step 2: populate unique UUIDs for all existing rows
        migrations.RunPython(populate_invite_codes, migrations.RunPython.noop),
        # Step 3: make it non-nullable and unique
        migrations.AlterField(
            model_name="tab",
            name="invite_code",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
