# Generated by Django 5.2.8 on 2026-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0013_tab_invite_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tabperson",
            unique_together={("tab", "name")},
        ),
        migrations.AlterField(
            model_name="bill",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                    ("PLN", "Polish Złoty"),
                    ("CZK", "Czech Crown"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("archived", "Archived")],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="from_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                    ("PLN", "Polish Złoty"),
                    ("CZK", "Czech Crown"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="to_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                    ("PLN", "Polish Złoty"),
                    ("CZK", "Czech Crown"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="settlement",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                    ("PLN", "Polish Złoty"),
                    ("CZK", "Czech Crown"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tab",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                    ("PLN", "Polish Złoty"),
                    ("CZK", "Czech Crown"),
                ],
                default="GBP",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tab",
            name="settlement_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CAD", "Canadian Dollar"),
                    ("TRY", "Turkish Lira"),
                    ("PLN", "Polish Złoty"),
                    ("CZK", "Czech Crown"),
                ],
                default="GBP",
                help_text="Currency used for calculating settlements",
                max_length=3,
            ),
        ),
        migrations.RemoveField(
            model_name="tabperson",
            name="email",
        ),
    ]
