# Generated by Django 5.2.13 on 2026-04-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0014_tab_is_demo_invite_code_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="settlement_total",
            field=models.IntegerField(
                blank=True,
                help_text="Sum of all claim settlement_amounts for this bill, in the tab's settlement currency (minor units)",
                null=True,
            ),
        ),
    ]
