# Generated by Django 5.2.8 on 2026-02-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0014_alter_tabperson_unique_together_alter_bill_currency_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExchangeRate",
        ),
    ]
