# Generated by Django 5.2.13 on 2026-04-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0015_add_bill_settlement_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="settlement_total",
        ),
    ]
