# Generated by Django 5.2.13 on 2026-05-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0016_remove_bill_settlement_total"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="settlement",
            index=models.Index(
                fields=["tab", "paid"], name="tabs_settle_tab_id_0bf5da_idx"
            ),
        ),
    ]
