# Generated by Django 6.0.5 on 2026-05-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0019_alter_bill_currency_alter_settlement_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="client_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id__isnull", False)),
                fields=("creator", "client_id"),
                name="uniq_bill_creator_client_id",
            ),
        ),
    ]
