# Generated by Django 6.0.5 on 2026-05-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0020_bill_client_id_bill_uniq_bill_creator_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tab",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
