# Generated by Django 6.0.5 on 2026-06-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0022_tabgroupmember_tab_period_index_tabgroup_tab_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="settled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this period was settled (null while still open)",
                null=True,
            ),
        ),
    ]
