# Generated by Django 6.0.5 on 2026-06-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0023_tab_settled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineitem",
            name="proportional",
            field=models.BooleanField(default=False),
        ),
    ]
