# Generated by Django 6.0.5 on 2026-08-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0024_lineitem_proportional"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Opt this tab into the unauthenticated read-only web view at /t/<public_slug>",
            ),
        ),
        migrations.AddField(
            model_name="tab",
            name="public_slug",
            field=models.SlugField(
                blank=True,
                help_text="Friendly URL for the public view. Auto-filled from the name when is_public is set.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
