# Generated by Django 6.0.5 on 2026-10-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabs", "0026_receipt_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptscan",
            name="readings",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
