# Generated by Django 5.2.8 on 2026-03-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninjatab_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="before_last_magic_link_sent_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_magic_link_sent_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
