# Generated by Django 5.2.13 on 2026-05-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninjatab_auth", "0002_user_before_last_magic_link_sent_dt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="analytics_opted_in",
            field=models.BooleanField(default=False),
        ),
    ]
