# Generated by Django 6.0.5 on 2026-05-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninjatab_auth", "0003_user_analytics_opted_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[("android", "Android"), ("ios", "iOS")],
                max_length=10,
            ),
        ),
    ]
