# Generated by Django 6.0.5 on 2026-05-30 20:29

import django.db.models.deletion
import ninjatab.utilities.fields
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninjatab_auth", "0004_user_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal"),
                            ("monzo", "Monzo"),
                            ("revolut", "Revolut"),
                        ],
                        max_length=20,
                    ),
                ),
                ("username", ninjatab.utilities.fields.EncryptedCharField()),
                ("is_preferred", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "provider"), name="uniq_user_payment_provider"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_preferred", True)),
                        fields=("user",),
                        name="uniq_preferred_payment_method_per_user",
                    ),
                ],
            },
        ),
    ]
