# Generated by Django 6.0.5 on 2026-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninjatab_auth", "0005_userpaymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpaymentmethod",
            name="provider",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("monzo", "Monzo"),
                    ("revolut", "Revolut"),
                    ("cashapp", "Cash App"),
                    ("venmo", "Venmo"),
                ],
                max_length=20,
            ),
        ),
    ]
