# Generated by Django 6.0.5 on 2026-06-03 18:22

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid6.uuid7, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("active", models.BooleanField(default=False)),
                ("value", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
